name: Releases
on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          preset: "conventionalcommits"
          github-token: ${{ secrets.github_token }}
          git-user-email: "wunderbar@mailbox.org"
          version-file: "composer.json"

      - name: Update composer
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          composer update --no-dev --optimize-autoloader
          git add *
          git commit -m "chore: update composer.lock after version bump" || exit 0
          git push

      - name: create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
