name: Releases
on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          preset: "conventionalcommits"
          github-token: ${{ secrets.github_token }}
          git-user-email: "wunderbar@mailbox.org"
          version-file: "composer.json"

      # As we use third party libs, and deliver a vendor directory,
      # we need to update composer.json to update the version of the plugin
      # in vendor/composer/installed.php so that kirby shows the right version
      - name: Update composer
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          composer update --no-dev --optimize-autoloader
          git add *
          git commit -m "chore: update composer after version bump" || exit 0
          git push

      - name: create release
        uses: softprops/action-gh-release@v2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          token: ${{ secrets.github_token }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
